version: '3.8'

networks:
  network:
   driver: bridge

volumes:
  postgres_data:

services:

  api:
    build:
      context: .
      dockerfile: SCSP.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_HTTP_PORTS=5160
    ports:
      - '5160:5160'
    networks:
      - network
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
